limit_req_zone $binary_remote_addr zone=aynur_deploy_hook:10m rate=5r/m;

server {
    listen 80;
    listen [::]:80;
    server_name orhan.cn www.orhan.cn;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name orhan.cn www.orhan.cn;

    ssl_certificate /etc/letsencrypt/live/orhan.cn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/orhan.cn/privkey.pem;
    ssl_session_timeout 5m;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
    ssl_prefer_server_ciphers on;

    root /var/lib/aynur-deploy/projects/orhan-blog/current;
    index index.html;
    client_max_body_size 10m;

    location = /_hooks/gitee/orhan-blog {
        client_max_body_size 64k;
        limit_req zone=aynur_deploy_hook burst=3 nodelay;
        limit_req_status 429;

        proxy_http_version 1.1;
        proxy_pass http://127.0.0.1:9091/v1/hooks/gitee/orhan-blog;
        proxy_pass_request_headers off;
        proxy_set_header Content-Type $http_content_type;
        proxy_set_header X-Gitee-Token $http_x_gitee_token;
        proxy_connect_timeout 2s;
        proxy_read_timeout 10s;
        proxy_send_timeout 10s;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
}
